export const CREAR_USUARIO = 'CREAR_USUARIO';
export const LOGIN_USER = 'LOGIN_USER'
export const USER_AUNTENTICADO = 'USER_AUNTENTICADO'
export const LOGOUT_USER = 'LOGOUT_USER';
export const ACTUALIZAR_USUARIO = "ACTUALIZAR_USUARIO";
export const ACTUALIZAR_CONTRASEÑA = "ACTUALIZAR_CONTRASEÑA";
export const EDITAR_FOTO = "EDITAR_FOTO";
export const EDITAR_FOTO_EXITO = "EDITAR_FOTO_EXITO";
export const OBTENER_TODOS_LOS_USUARIOS ="OBTENER_TODOS_LOS_USUARIOS";
export const DESCARGA_USER = "DESCARGA_USER";
export const DESCARGA_USER_EXITO = "DESCARGA_USER_EXITO";
export const DESCARGA_USER_ERROR = "DESCARGA_USER_ERROR";

